### ISSUE TITLE
graygelf stops proxying

### ISSUE THREAD

**Issue by disassembler** [wavded/graygelf#11]
I tried setting this up in our RD environment and it was working great but after a few hours, stopped getting any logs proxied to graylog. Here's the error I'm seeing in the logs:

```
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: invalid distance too far back
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: invalid distance too far back
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: invalid distance too far back
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
{ Error: invalid distance too far back
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
```

And this is my script for proxying:

```
var server = require('graygelf/server')().listen()
var client = require('graygelf')({ host: 'graylog', port: 12202})
server.pipe(client)
server.on('message', function (msg) { // intercept JSON parsed messages
//  console.log('received message', msg)
})

client.on('error', console.error)
server.on('error', console.error)
```

**Comment by wavded** [comment]
What version of Node are you running?

**Comment by disassembler** [comment]
v6.5.0

**Comment by wavded** [comment]
Unfortunately I don't have enough to go on to reproduce.  It's odd that it stops after running fine for a few hours.  Makes we wonder if its something in the Node zlib library itself.

**Comment by wavded** [comment]
Closing as old, if this is still an issue, please comment.
